apiVersion: v1
kind: Service
metadata:
  name: %2$s
  namespace: %1$s
spec:
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: %2$s
  namespace: %1$s
subsets:
- addresses:
  - ip: %3$s
